server:
  port: 8088
version: 2023091601

spring:
  devtools:
      restart:
        enabled: false
  profiles:
    active: prod
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  
--- #开发环境
  
spring:
  config:
    activate:
      on-profile: dev
      
printer: "Adobe PDF"
#printer: "HiTi"

serverHost: http://192.168.2.151:8081

--- #测试环境

server:
  port: 8089

spring:
  config:
    activate:
      on-profile: test

printer: PDF

serverHost: http://192.168.2.200:8088/rest-api

--- #生产环境

spring:
  config:
    activate:
      on-profile: prod

printer: HiTi

serverHost: https://magic.artfy.cc/rest-api
