name: Publish package to the Maven Central Repository
on:
  workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          # 一系列需要的密码
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}    # GPG 导出的那段长长的密钥
          gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}   # 自己设置的 GPG 密码
          nexus_username: wing4123     # sonatype 用户名（不是邮箱）
          nexus_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }} # sonatype 登录密码
